apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: joranvdm/hls-backend:web
          ports:
            - containerPort: 8000

          # 👇 THIS IS THE FIX
          command: ["python", "-m", "uvicorn"]
          args:
            - "main:app"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8000"

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DATABASE_URL
            - name: REDIS_CACHE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: REDIS_CACHE_URL
            - name: CELERY_BROKER_URL
              value: redis://redis-broker:6379/0

