apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  project: default

  # Where ArgoCD looks for your manifests
  source:
    repoURL: git@github.com:JoranVdm/hls-individual.git
    targetRevision: main
    path: backend/k8s/backend
    directory:
      recurse: true

  # Where ArgoCD deploys
  destination:
    name: docker-desktop
    namespace: default

  # Manual sync only
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  # auto-create namespace if missing
      - ApplyOutOfSyncOnly=true  # only apply resources that are out-of-sync
      - PruneLast=true          # prune after applying updates

  # Increase manifest generation timeout to 10 minutes
  info:
    - name: argocd.argoproj.io/timeout
      value: "600"  # seconds
