version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: streaming
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    working_dir: /app
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
      - ./app/videos:/app/videos
      - ./app/Cover:/app/Cover
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:mysecret@postgres:5432/streaming
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONPATH=/app
      - REDIS_CACHE_URL=${REDIS_CACHE_URL}

  worker:
    build: .
    working_dir: /app
    command: python -m celery -A celery_app.cel worker --loglevel=info --concurrency=12
    volumes:
      - ./app:/app
      - ./app/videos:/app/videos
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:mysecret@postgres:5432/streaming
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONPATH=/app
      - REDIS_CACHE_URL=${REDIS_CACHE_URL}

  beat:
    build: .
    working_dir: /app
    command: python -m celery -A celery_app.cel beat --loglevel=info
    volumes:
      - ./app:/app
      - ./app/videos:/app/videos
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:mysecret@postgres:5432/streaming
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONPATH=/app
      - REDIS_CACHE_URL=${REDIS_CACHE_URL}

volumes:
  pgdata:
