apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbCtwc3ljb3BnMjovL3Bvc3RncmVzOm15c2VjcmV0QHBvc3RncmVzOjU0MzIvc3RyZWFtaW5n
  REDIS_CACHE_URL: cmVkaXNzOi8vZGVmYXVsdDpBWnJxQUFJbmNERTFNVFUwTm1VM05XWm1PVFkwWldFM09ESmhZMlEyTlRFNU5tUTRaakEzTUhBeE16azJOVGdAd2l0dHktZG9nZmlzaC0zOTY1OC51cHN0YXNoLmlvOjYzNzk=
