apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbCtwc3ljb3BnMjovL3Bvc3RncmVzOm15c2VjcmV0QHBvc3RncmVzOjU0MzIvc3RyZWFtaW5n
  REDIS_CACHE_URL: cmVkaXNzOi8vZGVmYXVsdDpBWnJxQUFJbmNERTFNVFUwTm1VM05XWm1PVFkwWldFM09ESmhZMlEyTlRFNU5tUTRaakEzTUhBeE16azJOVGdAd2l0dHktZG9nZmlzaC0zOTY1OC51cHN0YXNoLmlvOjYzNzk=
  SUPABASE_URL: aHR0cHM6Ly9semxjYnFnd2N5dHBpdm5kc3pray5zdXBhYmFzZS5jbw==
  SUPABASE_SERVICE_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW14NmJHTmljV2QzWTNsMGNHbDJibVJ6ZW10cklpd2ljbTlzWlNJNkluTmxjblpwWTJWZmNtOXNaU0lzSW1saGRDSTZNVGMyT0RBd01ERXhNU3dpWlhod0lqb3lNRGd6TlRZeE1URXdmUS41TVJtQ0g4SllodVJWWnQ3SDlSak1VZnVwRXNBNjlyRE16c05mZzI5akVB

